### PR TITLE
Added applyWheresIn function

### PR DESCRIPTION
**Pull request by felipeumpierre**
Added the option to use `whereIn` from query builder.

Way to use:

```
$myRepository->applyWheresIn([
    ['id', [1, 2, 3, 4]]
])->all();
```

I closed my last PR because I saw that fork was a lot of commits behind.

### CODE REVIEW

**Comment by felipeumpierre** [comment]
ping @AaronJan

**Comment by AaronJan** [comment]
I'm late.. Thank you for your feedback! I'm a little bit busy recently.

There is a `whereIn` method in the `Eloquently` trait [here](https://github.com/AaronJan/Housekeeper/blob/master/src/Housekeeper/Abilities/Eloquently.php#L114)

You could use that instead, so the main `Repository` can keep concisely.

**Comment by AaronJan** [comment]
Ping @FelipeUmpierre

**Comment by felipeumpierre** [comment]
My bad, didn't notice that function.

Well done!

**Pull request closed without merging**
